/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-03-17 11:48:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\r\n");
      out.write("\t\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("\r\n");
      out.write("\t<title>sc.chinaz.com</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" charset=\"utf-8\" />\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"outer\">\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<div id=\"nav\">\r\n");
      out.write("\t\t  <div id=\"nav-left\">\r\n");
      out.write("\t\t    <div id=\"nav-right\">\r\n");
      out.write("    \t\t\t<ul>\r\n");
      out.write("    \t\t\t  <li><a href=\"http://sc.chinaz.com/\">ABOUT US</a></li>\r\n");
      out.write("    \t\t\t  <li><a href=\"http://sc.chinaz.com/\">PRODUCTS</a></li>\r\n");
      out.write("    \t\t\t  <li><a href=\"http://sc.chinaz.com/\">SERVICES</a></li>\r\n");
      out.write("    \t\t\t  <li><a href=\"http://sc.chinaz.com/\">SHOPPING CART</a></li>\r\n");
      out.write("    \t\t\t  <li><a href=\"http://sc.chinaz.com/\">NEW GADGETS</a></li>\r\n");
      out.write("    \t\t\t  <li><a href=\"http://sc.chinaz.com/\">REGISTER</a></li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"head\">\r\n");
      out.write("\t\t\t<div id=\"head-left\"></div>\r\n");
      out.write("\t\t\t<div id=\"head-right\"></div>\r\n");
      out.write("\t\t\t<div id=\"head-1\"></div>\r\n");
      out.write("\t\t\t<h1><span class=\"logo\"><span class=\"top\">top</span><span class=\"gadgets\">gadgets</span></span></h1>\r\n");
      out.write("\t\t\t<div id=\"navb\">\r\n");
      out.write("\t\t\t  <ul>\r\n");
      out.write("\t\t\t\t  <li><a href=\"http://sc.chinaz.com/\">HOME</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"http://sc.chinaz.com/\">CONTACT</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"head-2\"></div>\r\n");
      out.write("\t\t<div id=\"login\">\r\n");
      out.write("\t\t\t<div id=\"login-bot\">\r\n");
      out.write("\t\t\t\t<div id=\"login-box\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"login\"><em>user</em>login</h2>\r\n");
      out.write("\t\t\t\t\t<form action=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"login-username\">\r\n");
      out.write("\t\t\t\t\t\t\t<div><label for=\"username\">username</label>: <input type=\"text\" name=\"username\" value=\"\" id=\"username\" /></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div><label for=\"password\">password</label>: <input type=\"password\" name=\"password\" value=\"\" id=\"password\" /></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"login-button\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"image\" src=\"images/btn_login.gif\" name=\"l\" value=\"h\" id=\"l\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clear\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"reg\">\r\n");
      out.write("\t\t\t\t\t\t\t\tNew User? <a href=\"http://sc.chinaz.com/\">REGISTER for FREE</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"login-welcome\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<h2>Welcome</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>Don't forget to check <a href=\"http://sc.chinaz.com/\">free website templates</a> every day, because we add  a new free website template almost daily.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"body\">\r\n");
      out.write("\t\t\t<div id=\"body-bot\">\r\n");
      out.write("\t\t\t\t\t<h2><span>top <strong>GADGETS</strong> of this month</span></h2>\r\n");
      out.write("\t\t\t\t\t<div id=\"items\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/pic_1.jpg\" width=\"91\" height=\"105\" alt=\"iPod\" class=\"left\" />\r\n");
      out.write("\t\t\t\t\t\t\t<h3><a href=\"http://www.justwebtemplates.com\">Just Web Templates</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Even more websites all about website templates on <a href=\"http://www.justwebtemplates.com\">Just Web Templates</a>.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div><a href=\"http://sc.chinaz.com/\" class=\"details\">details</a> <a href=\"http://sc.chinaz.com/\" class=\"addtocart\">add to cart</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/pic_3.jpg\" width=\"91\" height=\"105\" alt=\"Plasma screen\" class=\"left\" />\r\n");
      out.write("\t\t\t\t\t\t\t<h3><a href=\"http://www.templatebeauty.com\">Template Beauty</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>If you're looking for beautiful and professionally made templates you can find them at <a href=\"http://www.templatebeauty.com\">Template Beauty</a>.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div><a href=\"http://sc.chinaz.com/\" class=\"details\">details</a> <a href=\"http://sc.chinaz.com/\" class=\"addtocart\">add to cart</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/pic_2.jpg\" width=\"91\" height=\"105\" alt=\"CD Player\" class=\"left\" />\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Plasma Screens</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>This is a template designed by free website templates for you for free you can replace all the text by your own   \t\t\ttext. </p>\r\n");
      out.write("\t\t\t\t\t\t\t<div><a href=\"http://sc.chinaz.com/\" class=\"details\">details</a> <a href=\"http://sc.chinaz.com/\" class=\"addtocart\">add to cart</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"divider\"></div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/pic_4.jpg\" width=\"91\" height=\"105\" alt=\"Camera\" class=\"left\" />\r\n");
      out.write("\t\t\t\t\t\t\t<h3><a href=\"http://sc.chinaz.com//forum/\">The Forum</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>If you're having problems editing the template please don't hesitate to ask for help on the <a href=\"http://sc.chinaz.com//forum/\">forum</a>.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div><a href=\"http://sc.chinaz.com/\" class=\"details\">details</a> <a href=\"http://sc.chinaz.com/\" class=\"addtocart\">add to cart</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"banner\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/pic_5.jpg\" width=\"256\" height=\"109\" alt=\"Nokia 6015i\" class=\"left\" />\r\n");
      out.write("\t\t\t\t\t\t<div id=\"banner-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3><a href=\"http://sc.chinaz.com/\">Nokia 6015i</a> (Verizon Wireless)</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t  <li>You can remove any link to our websites from this template you're  free to use the template without linking   \t\t\tback to us.</li>\r\n");
      out.write("\t\t\t\t\t\t\t  <li>This is just a place holder so you can see how the site would look like.</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"footloose\"><span class=\"logo\"><span class=\"top\">top</span><span class=\"gadgets\">gadgets</span></span></div>\r\n");
      out.write("\t\t\t\t\t\t<p><a href=\"http://sc.chinaz.com/\">Privacy Policy</a> <strong>&nbsp;:&nbsp;</strong> <a href=\"http://sc.chinaz.com/\">Terms &amp; Conditions</a> <br />\r\n");
      out.write("\t\t\t\t\t\t&copy; Copyright 2007. All rights reserved.</p>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"display:none\"><script src='http://v7.cnzz.com/stat.php?id=155540&web_id=155540' language='JavaScript' charset='gb2312'></script></div></body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
