/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-03-17 14:14:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Commerce;
import java.util.Vector;

public final class VueCommerceInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("model.Commerce");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Bours Bois</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 Vector<Commerce> commerceVector = (Vector<Commerce>) session.getAttribute("LCommerce");
      out.write('\r');
      out.write('\n');
 String nomI = (String)session.getAttribute("adresseMI"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"outer\">\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<div id=\"nav\">\r\n");
      out.write("\t\t  <div id=\"nav-left\">\r\n");
      out.write("\t\t    <div id=\"nav-right\">\r\n");
      out.write("    \t\t\t<ul>\r\n");
      out.write("    \t\t\t  <li><a href=>ABOUT US</a></li>\r\n");
      out.write("    \t\t\t  <li><a href=>PRODUCTS</a></li>\r\n");
      out.write("    \t\t\t  <li><a href=>SERVICES</a></li>\r\n");
      out.write("    \t\t\t  <li><a href=>SHOPPING CART</a></li>\r\n");
      out.write("    \t\t\t  <li><a href=>NEW GADGETS</a></li>\r\n");
      out.write("    \t\t\t  <li><a href=>REGISTER</a></li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"head\">\r\n");
      out.write("\t\t\t<div id=\"head-left\"></div>\r\n");
      out.write("\t\t\t<div id=\"head-right\"> </div>\t\t\t\r\n");
      out.write("\t\t\t<h1><span class=\"logo\"><span class=\"top\">Votre Espace producteur</span><span class=\"gadgets\">Filière Bois</span></span></h1>\r\n");
      out.write("\t\t\t<div id=\"navb\">\r\n");
      out.write("\t\t\t  <ul>\r\n");
      out.write("\t\t\t\t  <li><a href=\"Index.jsp\">HOME</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"\">CONTACT</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<form id=\"myForm\" method=\"get\" action=\"CommerceIndoServlet\">\r\n");
      out.write("\t\t\t<table border=\"0.3px\" style=\"margin: 0px auto;\">\r\n");
      out.write("\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t<th>IdCommerce</th>\r\n");
      out.write("\t\t\t\t\t<th>Nom Bois</th>\r\n");
      out.write("\t\t\t\t\t<th>Prix</th>\r\n");
      out.write("\t\t\t\t\t<th>Date disponible</th>\r\n");
      out.write("\t\t\t\t\t<th>Temps Dure</th>\r\n");
      out.write("\t\t\t\t\t<th>Nom producteur</th>\r\n");
      out.write("\t\t\t\t\t<th>Vendu</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t");

	
		if(commerceVector!=null)
			for(int i=0;i<commerceVector.size();i++){
		
			out.print("<tr>");
		
			out.print("<td>"+ commerceVector.get(i).getId() +"</td>");
			out.print("<td>"+ commerceVector.get(i).getNomB() +"</td>");
			out.print("<td>"+ commerceVector.get(i).getPrice() +"</td>");
			out.print("<td>"+ commerceVector.get(i).getDate() +"</td>");
			out.print("<td>"+ commerceVector.get(i).getDure() +"</td>");
			out.print("<td>"+ commerceVector.get(i).getNomP() +"</td>");
			out.print("<td>"+ commerceVector.get(i).getVendu() +"</td>");
			if(commerceVector.get(i).getVendu().equals("non")){
			
      out.write("\r\n");
      out.write("\t\t\t<td><a href=\"CommerceInfoServlet?nomI=");
out.print(nomI);
      out.write("&idC=");
out.print(commerceVector.get(i).getId());
      out.write("\">buy</a></td>\r\n");
      out.write("\t\t");
 
			}
		out.print("</tr>");
		
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div id=\"login\">\r\n");
      out.write("\t\t\t<div id=\"login-bot\">\r\n");
      out.write("\t\t\t\t<div id=\"login-box\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div id=\"login-username\">\r\n");
      out.write("\t\t\t\t\t\t<div><a href=\"EspaceInduServlet\" >Retourner à votre espace</a></div>\r\n");
      out.write("\t\t\t\t\t\t<div><a href=\"VueLoginOut.jsp\" >Log Out</a></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"login-welcome\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<h2>Bienvenue sur FILIERE BOIS</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>Ce website est maintenu par FILIERE BOIS;\r\n");
      out.write("\t\t\t\t\t\t\tet a &eacute;t&eacute; d&eacute;velopp&eacute; par FILIERE BOIS \r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
